import type { MarketplacePlugin } from './curated-registry.ts'

/**
 * 离线可用的 dsh 社区插件目录（真实数据，打包进客户端，无需联网即可展示/搜索）。
 *
 * 背景与为什么要内置它：
 * 桌面端主进程通过宿主代理去 `api.github.com` 拉取插件时，在国内等网络环境下经常连不通
 * （主进程 fetch 抛异常 → 代理返回 502），导致市场「默认空白 + 搜索全失败 + 没有 star 数」。
 * 这份目录用**我（构建期/维护期）从 GitHub 真实抓取的数据**预先填好，保证：
 *   1. 哪怕 GitHub 完全不可达，市场默认也展示一份真实可用的 dsh 社区插件清单（带真实 star）；
 *   2. 搜索完全在本地进行（中英文意图匹配，见 curated-registry.ts 的 `localSearch`），
 *      如输入「cc-connect / 翻译 / 文档」都能从这份目录里命中真实项目；
 *   3. 「加载更多」对这份本地目录做分页，不依赖网络。
 *
 * 当运行环境能连通 GitHub 时，MarketplacePanel 会在后台拉取实时仓库并合并补充（同 id 覆盖刷新 star）；
 * 连不通则以这份目录为准，不打断使用。
 *
 * 数据抓取时间：2026-08-17；star 数为当时的真实值，后续可通过刷新/连通 GitHub 更新。
 * 如需扩充，直接往这里追加 `gh-<owner>/<repo>` 条目即可（id 与 GitHub 映射保持一致以便去重合并）。
 */
export const COMMUNITY_PLUGINS: readonly MarketplacePlugin[] = Object.freeze([
  {
    id: 'gh-deepseek-ai/deepseek-harness',
    name: 'DeepSeek Harness（核心框架）',
    description: 'DeepSeek 开源的 AI Agent 运行框架，奉行「一切皆插件」：模型、工具、UI、调度全部可插拔。所有 dsh 插件的运行基座。',
    author: 'deepseek-ai',
    repository: 'https://github.com/deepseek-ai/deepseek-harness',
    installSpec: 'github:deepseek-ai/deepseek-harness',
    tags: ['deepseek', 'harness', 'framework', 'core', 'dsh', '框架', '核心', '智能体', 'agent'],
    stars: 144743,
    source: 'curated',
  },
  {
    id: 'gh-chenhg5/cc-connect',
    name: 'CC Connect（cc-connect）',
    description: '把本地 AI 编程智能体（Claude Code、Cursor、Codex、Gemini CLI 等）桥接到飞书/钉钉/Slack/Telegram/Discord/微信等聊天平台，随时随地用 IM 跟你的开发助手对话，多数平台无需公网 IP。',
    author: 'chenhg5',
    repository: 'https://github.com/chenhg5/cc-connect',
    installSpec: 'github:chenhg5/cc-connect',
    tags: ['cc-connect', 'cc', 'connect', '飞书', '钉钉', 'slack', 'telegram', 'discord', '微信', 'im', '远程', '消息', '桥接'],
    stars: 15005,
    source: 'curated',
  },
  {
    id: 'gh-nexu-io/open-design',
    name: 'Open Design',
    description: '最佳 DeepSeek Harness 设计插件：把编码智能体变成设计引擎，可生成原型、落地页、仪表盘、幻灯片、图片与视频，支持 HTML/PDF/PPTX/MP4 导出。',
    author: 'nexu-io',
    repository: 'https://github.com/nexu-io/open-design',
    installSpec: 'github:nexu-io/open-design',
    tags: ['design', '设计', 'prototype', '原型', 'ui', '落地页', '幻灯片', 'ai-design', '导出'],
    stars: 88060,
    source: 'curated',
  },
  {
    id: 'gh-CherryHQ/cherry-studio',
    name: 'Cherry Studio',
    description: 'AI 生产力工作台：智能聊天、自主智能体、300+ 助手，统一接入各家前沿大模型。',
    author: 'CherryHQ',
    repository: 'https://github.com/CherryHQ/cherry-studio',
    installSpec: 'github:CherryHQ/cherry-studio',
    tags: ['chat', 'assistant', '助手', 'llm', '工作室', 'productivity', '聊天'],
    stars: 50630,
    source: 'curated',
  },
  {
    id: 'gh-Hmbown/CodeWhale',
    name: 'CodeWhale',
    description: '开源、社区驱动的 Agent 运行框架，支持 DeepSeek、Claude、Qwen、Kimi 等多模型，Rust 编写，终端 TUI 体验。',
    author: 'Hmbown',
    repository: 'https://github.com/Hmbown/CodeWhale',
    installSpec: 'github:Hmbown/CodeWhale',
    tags: ['agent', 'harness', '框架', 'cli', 'terminal', 'rust', '智能体', '终端'],
    stars: 40828,
    source: 'curated',
  },
  {
    id: 'gh-titanwings/colleague-skill',
    name: 'Colleague Skill',
    description: '把冰冷的离别化为温暖的 Skill，数字生命 1.0：为智能体添加人格与记忆的元技能插件。',
    author: 'titanwings',
    repository: 'https://github.com/titanwings/colleague-skill',
    installSpec: 'github:titanwings/colleague-skill',
    tags: ['skill', '技能', 'persona', '数字生命', 'meta-skill', '人格', 'memory'],
    stars: 23067,
    source: 'curated',
  },
  {
    id: 'gh-tt-a1i/archify',
    name: 'Archify',
    description: '为智能体生成精美、可验证的架构图/流程图/时序图/数据流图/生命周期图，输出自包含 HTML，可导出。',
    author: 'tt-a1i',
    repository: 'https://github.com/tt-a1i/archify',
    installSpec: 'github:tt-a1i/archify',
    tags: ['diagram', '架构图', '流程图', 'sequence', 'svg', 'diagram-as-code', '图表'],
    stars: 13743,
    source: 'curated',
  },
  {
    id: 'gh-anywhere-labs/deepseek-harness-desktop',
    name: 'DeepSeek Harness Desktop（anywhere-labs）',
    description: '为 DeepSeek Harness（DSH）插件生态打造的现代化桌面端方案，万物皆插件，桌面本身也是插件。',
    author: 'anywhere-labs',
    repository: 'https://github.com/anywhere-labs/deepseek-harness-desktop',
    installSpec: 'github:anywhere-labs/deepseek-harness-desktop',
    tags: ['desktop', '桌面端', 'dsh', 'dsh-plugin', 'cordis'],
    stars: 11087,
    source: 'curated',
  },
  {
    id: 'gh-YaoApp/yao',
    name: 'Yao',
    description: '把你的智能体与工作区集中到一处、跨设备可用：看板管理任务，支持桌面/移动/浏览器/API，可自托管。',
    author: 'YaoApp',
    repository: 'https://github.com/YaoApp/yao',
    installSpec: 'github:YaoApp/yao',
    tags: ['agent', 'workspace', '工作区', 'task', '看板', 'self-hosted', '任务'],
    stars: 7654,
    source: 'curated',
  },
  {
    id: 'gh-awesome-dsh-plugin/awesome-dsh-plugin',
    name: 'Awesome DSH Plugin（精选列表）',
    description: 'DeepSeek Harness（dsh）插件精选列表，中英双语，按分类整理社区优质插件，方便发现与安装。',
    author: 'awesome-dsh-plugin',
    repository: 'https://github.com/awesome-dsh-plugin/awesome-dsh-plugin',
    installSpec: 'github:awesome-dsh-plugin/awesome-dsh-plugin',
    tags: ['awesome', 'list', '精选', '清单', 'dsh-plugin', '资源'],
    stars: 7225,
    source: 'curated',
  },
  {
    id: 'gh-Q00/ouroboros',
    name: 'Ouroboros',
    description: 'Agent OS：智能体自我进化，分级评估与预算化演进循环；提供 MCP 服务，支持 Claude Code、Codex、OpenCode 等 13 种运行时。',
    author: 'Q00',
    repository: 'https://github.com/Q00/ouroboros',
    installSpec: 'github:Q00/ouroboros',
    tags: ['agent-os', 'mcp', 'orchestration', '评估', 'llm-orchestration', '调度'],
    stars: 5495,
    source: 'curated',
  },
  {
    id: 'gh-Devin-AXIS/iPolloWork',
    name: 'iPolloWork',
    description: '次世代、可源码可见的 AI 工作空间，自带可演进的智能体运行时，覆盖代码、设计、演示、网站与视频。',
    author: 'Devin-AXIS',
    repository: 'https://github.com/Devin-AXIS/iPolloWork',
    installSpec: 'github:Devin-AXIS/iPolloWork',
    tags: ['workspace', '工作空间', 'ai-work', 'agent', '工作区'],
    stars: 4087,
    source: 'curated',
  },
  {
    id: 'gh-zhukunpenglinyutong/desktop-cc-gui',
    name: 'Desktop CC GUI',
    description: '多引擎 AI 编程桌面客户端（Tauri）：把 Claude Code、Codex、Gemini、OpenCode、DeepSeek Harness 等整合到一个 GUI。',
    author: 'zhukunpenglinyutong',
    repository: 'https://github.com/zhukunpenglinyutong/desktop-cc-gui',
    installSpec: 'github:zhukunpenglinyutong/desktop-cc-gui',
    tags: ['desktop', '桌面', 'tauri', 'gui', 'coding-agent', '客户端'],
    stars: 4023,
    source: 'curated',
  },
  {
    id: 'gh-zhu1090093659/dsh-web-ui',
    name: 'DSH Web UI 增强包',
    description: 'DeepSeek Harness（DSH）Web UI 的插件与皮肤集合：任务看板、Git 图谱、右侧面板、手机端远程界面、实时 token 统计、皮肤中心。',
    author: 'zhu1090093659',
    repository: 'https://github.com/zhu1090093659/dsh-web-ui',
    installSpec: 'github:zhu1090093659/dsh-web-ui',
    tags: ['web-ui', 'ui', 'skin', '皮肤', '看板', 'git', 'dashboard', 'dsh-plugin'],
    stars: 3966,
    source: 'curated',
  },
  {
    id: 'gh-xiaobright/dsh-anchored-standard',
    name: 'DSH Anchored Standard',
    description: '两阶段 DeepSeek Harness 预设：先最小对齐引导，再加载完整 Standard 工具集，提升项目规范与一致性。',
    author: 'xiaobright',
    repository: 'https://github.com/xiaobright/dsh-anchored-standard',
    installSpec: 'github:xiaobright/dsh-anchored-standard',
    tags: ['preset', '预设', 'standard', '规范', 'dsh-plugin'],
    stars: 3364,
    source: 'curated',
  },
  {
    id: 'gh-edison7009/EchoBird',
    name: 'EchoBird',
    description: '一键安装与模型切换：Claude Code、Codex CLI、Grok、DeepSeek Harness、Kimi Code、Qwen Code、OpenCode 等集成到统一入口。',
    author: 'edison7009',
    repository: 'https://github.com/edison7009/EchoBird',
    installSpec: 'github:edison7009/EchoBird',
    tags: ['installer', '安装', 'model-switch', '模型切换', 'launcher', '入口'],
    stars: 3061,
    source: 'curated',
  },
  {
    id: 'gh-Anionex/dsh-vision-toolkit',
    name: 'DSH Vision Toolkit',
    description: '给纯文本模型加上视觉能力：带意图的图片问答、长截图 OCR、UI 还原、像素对比；DeepSeek Harness 原生插件。',
    author: 'Anionex',
    repository: 'https://github.com/Anionex/dsh-vision-toolkit',
    installSpec: 'github:Anionex/dsh-vision-toolkit',
    tags: ['vision', '视觉', 'ocr', 'image', '图片', 'ui-restoration', '多模态', '截屏'],
    stars: 592,
    source: 'curated',
  },
  {
    id: 'gh-ccch1mneyyy/dsh-TUI',
    name: 'DSH TUI',
    description: '官方公众号收录的 TUI 补位插件：Claude Code 风格，鲸鱼顶栏、实时状态、流式思考、双击 Esc 回滚、上下文进度+TTS；npm 一键装。',
    author: 'ccch1mneyyy',
    repository: 'https://github.com/ccch1mneyyy/dsh-TUI',
    installSpec: 'github:ccch1mneyyy/dsh-TUI',
    tags: ['tui', 'terminal', '终端', 'cli', 'whale', '鲸鱼', '命令行'],
    stars: 1766,
    source: 'curated',
  },
  {
    id: 'gh-omdsh-dev/DSH-better-sidebar',
    name: 'DSH Better Sidebar',
    description: '开放式侧边栏底座，支持三方拓展注册新侧边栏页面；内置文件渲染编辑、终端、Git、子代理页面。',
    author: 'omdsh-dev',
    repository: 'https://github.com/omdsh-dev/DSH-better-sidebar',
    installSpec: 'github:omdsh-dev/DSH-better-sidebar',
    tags: ['sidebar', '侧边栏', 'workspace', '文件', 'git', 'terminal', '面板'],
    stars: 1882,
    source: 'curated',
  },
  {
    id: 'gh-lhh010/dsh-ui-whale',
    name: 'DSH UI Whale（像素鲸鱼桌宠）',
    description: 'DSH Web UI 全手绘像素鲸鱼伙伴插件：会话标题栏常驻，眨眼摆尾、思考时活动、回合结束喷水、点击冒爱心，零核心改动。',
    author: 'lhh010',
    repository: 'https://github.com/lhh010/dsh-ui-whale',
    installSpec: 'github:lhh010/dsh-ui-whale',
    tags: ['whale', '鲸鱼', 'pet', '桌宠', 'ui', '皮肤', 'skin', '陪伴'],
    stars: 29,
    source: 'curated',
  },
  {
    id: 'gh-whiteguo233/dsh-cc-connect',
    name: 'DSH CC Connect',
    description: '通过 cc-connect 远程使用 DeepSeek Harness（DSH），把 DSH 接入聊天平台桥接。',
    author: 'whiteguo233',
    repository: 'https://github.com/whiteguo233/dsh-cc-connect',
    installSpec: 'github:whiteguo233/dsh-cc-connect',
    tags: ['cc-connect', 'cc', 'connect', 'bridge', '桥接', '远程', 'dsh-plugin'],
    stars: 2,
    source: 'curated',
  },
])
